---
- name: Install apache2
  package:
    name: apache2
    state: present

- name: Create be directory
  file:
    path: /tmp/befiles
    state: directory

- name: Download from S3
  shell: |
          aws s3 cp s3://skillup-santose-s3-01/backend.zip /tmp/befiles/backend.zip

- name: Extract backend.zip to /var/www/html/
  unarchive:  
    src: /tmp/befiles/backend.zip
    dest: /var/www/html/
    remote_src: yes

- name: Remove default index.html to use index.php instead
  file:
    path: /var/www/html/index.html
    state: absent

- name: Start apache2
  service:
    name: apache2
    state: started
    enabled: yes
